### ISSUE TITLE
Mailbeez - Installation error

### ISSUE THREAD

**Issue by wa4u** [loadedcommerce/Loaded6CE#97]
Hello Cord,

There is an error in mailbeez installation. I tried at different accounts, installation did not work.
Can you please give me direction if anything is missing.

Thanks
Kiran

![screenshot_1](https://cloud.githubusercontent.com/assets/3207057/15214620/b0dd0100-186b-11e6-8a7f-6e86cb866408.png)

**Comment by cord** [comment]
hey kiran,

looks like your server blocks the connection to cloudbeez.com

**Comment by saliozzia** [comment]
why or how would our server do that?

**Comment by saliozzia** [comment]
@cord 
can you tell us what ip or domain it is trying to access so we can have our server techs reproduce this call?

**Comment by cord** [comment]
its cloudbeez.com / mailbeez.com

you can also check the php error log if something else breaks.

normally this is not an issue.

**Comment by wa4u** [comment]
Here is log file;

```
====================================================================.
========================== INSTALLATION LOG ========================'

[2016/05/12 08:29:04] Host: Linux host1ub.thereactorhosting.com 2.6.32-504.16.2.el6.x86_64 #1 SMP Wed Apr 22 06:48:29 UTC 2015 x86_64
[2016/05/12 08:29:04] Operating system: Linux
[2016/05/12 08:29:04] Memory limit: 128M
[2016/05/12 08:29:04] Max execution time: 3600
[2016/05/12 08:29:04] Server request: content/mailbeez_core_installer_intro/en?p=YTo0OntzOjY6ImRvbWFpbiI7czoxOToia2lyYW4udHJoc2VjdXJlLmNvbSI7czoxOiJwIjtzOjk6ImNyZWxvYWRlZCI7czoxOiJhIjtzOjU6Ik1IX0lEIjtzOjM6InVybCI7czo1NjoiYUhSMGNEb3ZMMnRwY21GdUxuUnlhSE5sWTNWeVpTNWpiMjB2YldGcGJHSmxaWG92WVdSdGFXNHYiO30%253D
[2016/05/12 08:29:04] Server request: content/mailbeez_core_installer_steps/en?p=YTo0OntzOjY6ImRvbWFpbiI7czoxOToia2lyYW4udHJoc2VjdXJlLmNvbSI7czoxOiJwIjtzOjk6ImNyZWxvYWRlZCI7czoxOiJhIjtzOjU6Ik1IX0lEIjtzOjM6InVybCI7czo1NjoiYUhSMGNEb3ZMMnRwY21GdUxuUnlhSE5sWTNWeVpTNWpiMjB2YldGcGJHSmxaWG92WVdSdGFXNHYiO30%253D
[2016/05/12 08:29:04] Server request: content/mailbeez_core_installer_final/en?p=YTo0OntzOjY6ImRvbWFpbiI7czoxOToia2lyYW4udHJoc2VjdXJlLmNvbSI7czoxOiJwIjtzOjk6ImNyZWxvYWRlZCI7czoxOiJhIjtzOjU6Ik1IX0lEIjtzOjM6InVybCI7czo1NjoiYUhSMGNEb3ZMMnRwY21GdUxuUnlhSE5sWTNWeVpTNWpiMjB2YldGcGJHSmxaWG92WVdSdGFXNHYiO30%253D
[2016/05/12 08:29:04] Server request: content/mailbeez_core_common/en?p=YTo0OntzOjY6ImRvbWFpbiI7czoxOToia2lyYW4udHJoc2VjdXJlLmNvbSI7czoxOiJwIjtzOjk6ImNyZWxvYWRlZCI7czoxOiJhIjtzOjU6Ik1IX0lEIjtzOjM6InVybCI7czo1NjoiYUhSMGNEb3ZMMnRwY21GdUxuUnlhSE5sWTNWeVpTNWpiMjB2YldGcGJHSmxaWG92WVdSdGFXNHYiO30%253D
[2016/05/12 08:29:08] Execute AJAX handler: onCheckRequirement
[2016/05/12 08:29:08] System check: phpVersion
[2016/05/12 08:29:08] Requirement phpVersion +OK
[2016/05/12 08:29:09] Execute AJAX handler: onCheckRequirement
[2016/05/12 08:29:09] System check: safeMode
[2016/05/12 08:29:09] Requirement safeMode +OK
[2016/05/12 08:29:10] Execute AJAX handler: onCheckRequirement
[2016/05/12 08:29:10] System check: curlLibrary
[2016/05/12 08:29:10] Requirement curlLibrary +OK
[2016/05/12 08:29:11] Execute AJAX handler: onCheckRequirement
[2016/05/12 08:29:11] System check: liveConnection
[2016/05/12 08:29:11] Server request: ping?p=YTo0OntzOjY6ImRvbWFpbiI7czoxOToia2lyYW4udHJoc2VjdXJlLmNvbSI7czoxOiJwIjtzOjk6ImNyZWxvYWRlZCI7czoxOiJhIjtzOjU6Ik1IX0lEIjtzOjM6InVybCI7czo1NjoiYUhSMGNEb3ZMMnRwY21GdUxuUnlhSE5sWTNWeVpTNWpiMjB2YldGcGJHSmxaWG92WVdSdGFXNHYiO30%253D
[2016/05/12 08:29:11] Server request: ping
[2016/05/12 08:29:11] Request information: Array
(
    [url] => http://staging.cloudbeez.com/api/public/v1/ping?p=YTo0OntzOjY6ImRvbWFpbiI7czoxOToia2lyYW4udHJoc2VjdXJlLmNvbSI7czoxOiJwIjtzOjk6ImNyZWxvYWRlZCI7czoxOiJhIjtzOjU6Ik1IX0lEIjtzOjM6InVybCI7czo1NjoiYUhSMGNEb3ZMMnRwY21GdUxuUnlhSE5sWTNWeVpTNWpiMjB2YldGcGJHSmxaWG92WVdSdGFXNHYiO30%253D
    [content_type] => 
    [http_code] => 0
    [header_size] => 0
    [request_size] => 0
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0
    [namelookup_time] => 0
    [connect_time] => 0
    [pretransfer_time] => 0
    [size_upload] => 0
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 0
    [redirect_time] => 0
    [certinfo] => Array
        (
        )

    [primary_ip] => 
    [primary_port] => 0
    [local_ip] => 
    [local_port] => 0
    [redirect_url] => 
)

[2016/05/12 08:29:11] Handler error (onCheckRequirement): Server responded had no response.
[2016/05/12 08:29:11] Trace log:
#0 /home/kirantest/public_html/mailbeez/mailhive/cloudbeez/cloudloader/php/Cloudloader.php(116): Cloudloader->requestServerData('ping', '', 'public')
#1 /home/kirantest/public_html/mailbeez/mailhive/cloudbeez/cloudloader/php/Cloudloader.php(91): Cloudloader->onCheckRequirement()
#2 /home/kirantest/public_html/mailbeez/mailhive/cloudbeez/cloudloader/php/CloudloaderInit.php(26): Cloudloader->run()
#3 /home/kirantest/public_html/mailbeez/mailhive/cloudbeez/cloudloader_core.php(29): include('/home/kirantest...')
#4 /home/kirantest/public_html/mailbeez/mailhive/cloudbeez/cloudloader/bootstrap/inc_mailbeez.php(25): require_once('/home/kirantest...')
#5 /home/kirantest/public_html/mailbeez/admin/mailbeez.php(51): require_once('/home/kirantest...')
#6 {main}
```

**Comment by wa4u** [comment]
http://staging.cloudbeez.com/api/public/v1/ is not found.

staging.cloudbeez.com’s server DNS address could not be found.
ERR_NAME_NOT_RESOLVED

**Comment by cord** [comment]
please remove /mailhive/cloudbeez/dev_environment.php

will remove that from git as well
